services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: address-extractor-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GEOCODING_API_URL=http://api:5000
    depends_on:
      - api
    networks:
      - address-extractor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  api:
    image: geocoding-service:latest
    container_name: address-extractor-api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=5000
      - DEBUG=false
    networks:
      - address-extractor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  address-extractor-network:
    name: address-extractor-network
    driver: bridge
